# Generated by Django 4.0.4 on 2023-05-24 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('workstatus', models.CharField(choices=[('Yes', 'Completed'), ('No', 'Not Completed')], max_length=5)),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exfd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('FM', 'Female')], max_length=10)),
                ('rollno', models.CharField(max_length=15)),
                ('collegename', models.CharField(choices=[('AANM', 'AANM VVRSR POLYTECHNIC - GVL'), ('SVGP', 'SV GOVT POLYTECHNIC'), ('AANMR', 'AANM VVRSR POLYTECHNIC - RJYD')], max_length=7)),
                ('impf', models.ImageField(default='profile.png', upload_to='profile/')),
                ('d', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
