# Generated by Django 4.0.4 on 2023-06-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DailyWorkStatus', '0002_contact_model'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact_model',
            table='contact_Info',
        ),
    ]
